// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoa2APur6mgCk_gvSybbgfWTY4-vJ5DJs',
    appId: '1:650935915807:android:6cb9fa57db4059ab040c2a',
    messagingSenderId: '650935915807',
    projectId: 'aisai-app',
    databaseURL: 'https://aisai-app-default-rtdb.firebaseio.com',
    storageBucket: 'aisai-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBae_MHEr_5meeEDbc4MDxGEx6O85y4u6Q',
    appId: '1:650935915807:ios:48bb47fd90f4b334040c2a',
    messagingSenderId: '650935915807',
    projectId: 'aisai-app',
    databaseURL: 'https://aisai-app-default-rtdb.firebaseio.com',
    storageBucket: 'aisai-app.appspot.com',
    iosClientId: '650935915807-230pt14f6u0ksq1tp3cns5t6708uap7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.aisaiApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg9Qf5zYbyZj0SHne5LR2H1TCCxhBY2rs',
    appId: '1:650935915807:web:b0ba27f074e1c264040c2a',
    messagingSenderId: '650935915807',
    projectId: 'aisai-app',
    authDomain: 'aisai-app.firebaseapp.com',
    databaseURL: 'https://aisai-app-default-rtdb.firebaseio.com',
    storageBucket: 'aisai-app.appspot.com',
    measurementId: 'G-G22T3JZ5EL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBae_MHEr_5meeEDbc4MDxGEx6O85y4u6Q',
    appId: '1:650935915807:ios:48bb47fd90f4b334040c2a',
    messagingSenderId: '650935915807',
    projectId: 'aisai-app',
    databaseURL: 'https://aisai-app-default-rtdb.firebaseio.com',
    storageBucket: 'aisai-app.appspot.com',
    iosClientId: '650935915807-230pt14f6u0ksq1tp3cns5t6708uap7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.aisaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg9Qf5zYbyZj0SHne5LR2H1TCCxhBY2rs',
    appId: '1:650935915807:web:a2ca1d95415f6589040c2a',
    messagingSenderId: '650935915807',
    projectId: 'aisai-app',
    authDomain: 'aisai-app.firebaseapp.com',
    databaseURL: 'https://aisai-app-default-rtdb.firebaseio.com',
    storageBucket: 'aisai-app.appspot.com',
    measurementId: 'G-NQLTKNF8KP',
  );

}