import '../../../model/user_model/user_model.dart';

class UserListViewModel {
  final Map<String, List<UserModel>> regionUsers = {
    "おすすめのユーザー": [
      UserModel(
        uid: '1',
        name: 'User1',
        age: 25,
        gender: '男性',
        bio: 'プロフィール1',
        email: '',
        password: 'password1',
        profileImagePath: 'assets/image/us2.jpg',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
      UserModel(
        uid: '2',
        name: 'User2',
        age: 30,
        gender: '女性',
        bio: 'プロフィール2',
        email: '',
        password: 'password2',
        profileImagePath: '',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
      UserModel(
        uid: '3',
        name: 'User3',
        age: 28,
        gender: 'その他',
        bio: 'プロフィール3',
        email: '',
        password: 'password3',
        profileImagePath: 'assets/image/us3.jpg',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
      UserModel(
        uid: '4',
        name: 'User4',
        age: 22,
        gender: '男性',
        bio: 'プロフィール4',
        email: '',
        password: 'password4',
        profileImagePath: 'assets/image/us4.jpg',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
      UserModel(
        uid: '5',
        name: 'User5',
        age: 26,
        gender: '女性',
        bio: 'プロフィール5',
        email: '',
        password: 'password5',
        profileImagePath: 'assets/image/us5.jpg',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
    ],
    "辺野古エイサー": [
      UserModel(
        uid: '6',
        name: 'User6',
        age: 22,
        gender: '男性',
        bio: 'プロフィール6',
        email: '',
        password: 'password6',
        profileImagePath: 'assets/image/us1.png',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
      UserModel(
        uid: '7',
        name: 'User7',
        age: 26,
        gender: '女性',
        bio: 'プロフィール7',
        email: '',
        password: 'password7',
        profileImagePath: 'assets/image/us2.jpg',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
      UserModel(
        uid: '8',
        name: 'User8',
        age: 24,
        gender: '男性',
        bio: 'プロフィール8',
        email: '',
        password: 'password8',
        profileImagePath: 'assets/image/us3.jpg',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
    ],
    "全島エイサー": [
      UserModel(
        uid: '9',
        name: 'User9',
        age: 20,
        gender: '男性',
        bio: 'プロフィール9',
        email: '',
        password: 'password9',
        profileImagePath: 'assets/image/us4.jpg',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
      UserModel(
        uid: '10',
        name: 'User10',
        age: 29,
        gender: '女性',
        bio: 'プロフィール10',
        email: '',
        password: 'password10',
        profileImagePath: '',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
      UserModel(
        uid: '11',
        name: 'User11',
        age: 31,
        gender: '男性',
        bio: 'プロフィール11',
        email: '',
        password: 'password11',
        profileImagePath: '',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
      UserModel(
        uid: '12',
        name: 'User12',
        age: 24,
        gender: '女性',
        bio: 'プロフィール12',
        email: '',
        password: 'password12',
        profileImagePath: '',
        backgroundImagePath: '',
        questModel: null,
        userLocation: '',
        youthGroupFlag: false,
        seinennkai: '非会員',
        userOccpation: '',
      ),
    ],
  };
}
